package TemplateAdmin;


import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;


public class MainFrameAdmin extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();

     ViewTable.TableKolam v_kolam;
     ViewTable.TablePopulasi v_populasi;
     ViewTable.TableHargaIkan v_harga;
     ViewTable.TablePetugas v_petugas;
     ViewTable.TableDataIkan v_dataikan;
     ViewTable.TablePemijahan v_pemijahan;
     ViewTable.TablePemberianPakan v_pakan;
     ViewTable.TableStokIndukan v_stokindukan;
     ViewTable.TableOpname v_opname;
     ViewTable.TableRiwayatPengadaan v_pengadaan;
     Connection con;
     Statement stat;
     ResultSet rs;
     String sql;
    public MainFrameAdmin() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        
        v_kolam = new ViewTable.TableKolam();
        v_populasi = new ViewTable.TablePopulasi();
        v_harga = new ViewTable.TableHargaIkan();
        v_petugas = new ViewTable.TablePetugas();
        v_dataikan = new ViewTable.TableDataIkan();
        v_pemijahan = new ViewTable.TablePemijahan();
        v_pakan = new ViewTable.TablePemberianPakan();
        v_stokindukan = new ViewTable.TableStokIndukan();
        v_opname = new ViewTable.TableOpname();
        v_pengadaan = new ViewTable.TableRiwayatPengadaan();
        
        ChangePanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
//        c.gridx=0;
//        c.gridy=0;
        c.weightx = 575;
        c.weighty = 995;
        ChangePanel.add(v_kolam,c);
        ChangePanel.add(v_populasi,c);
        ChangePanel.add(v_harga, c);
        ChangePanel.add(v_petugas, c);
        ChangePanel.add(v_dataikan, c);
        ChangePanel.add(v_pemijahan, c);
        ChangePanel.add(v_pakan, c);
        ChangePanel.add(v_stokindukan, c);
        ChangePanel.add(v_opname, c);
        ChangePanel.add(v_pengadaan, c);
        
        ChangePanel.setVisible(true);
        v_kolam.setVisible(true);
        v_populasi.setVisible(false);
        v_harga.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        btn_viewkolam = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_viewharga = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_viewpopulasi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_viewpetugas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_viewpakan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_viewpemijahan = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_viewstokindukan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_viewikan = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_viewopname = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_viewpengadaan = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ChangePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setPreferredSize(new java.awt.Dimension(1066, 82));

        judul.setFont(new java.awt.Font("Consolas", 0, 29)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Data Kolam");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(97, 212, 195));
        jPanel4.setPreferredSize(new java.awt.Dimension(221, 768));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Webp.net-resizeimage.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BBIAT");

        jSeparator1.setBackground(new java.awt.Color(36, 47, 65));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel7.setBackground(new java.awt.Color(97, 212, 195));

        btn_viewkolam.setBackground(new java.awt.Color(97, 203, 208));
        btn_viewkolam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewkolamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewkolamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewkolamMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Kolam");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/fish-3-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewkolamLayout = new javax.swing.GroupLayout(btn_viewkolam);
        btn_viewkolam.setLayout(btn_viewkolamLayout);
        btn_viewkolamLayout.setHorizontalGroup(
            btn_viewkolamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewkolamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewkolamLayout.setVerticalGroup(
            btn_viewkolamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewkolamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        btn_viewharga.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewhargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewhargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewhargaMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Harga");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/price-tag-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewhargaLayout = new javax.swing.GroupLayout(btn_viewharga);
        btn_viewharga.setLayout(btn_viewhargaLayout);
        btn_viewhargaLayout.setHorizontalGroup(
            btn_viewhargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewhargaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewhargaLayout.setVerticalGroup(
            btn_viewhargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewhargaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewpopulasi.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewpopulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewpopulasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewpopulasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewpopulasiMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data Populasi");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/fish-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewpopulasiLayout = new javax.swing.GroupLayout(btn_viewpopulasi);
        btn_viewpopulasi.setLayout(btn_viewpopulasiLayout);
        btn_viewpopulasiLayout.setHorizontalGroup(
            btn_viewpopulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewpopulasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewpopulasiLayout.setVerticalGroup(
            btn_viewpopulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewpopulasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewpetugas.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewpetugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewpetugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewpetugasMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Data Petugas");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/workers-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewpetugasLayout = new javax.swing.GroupLayout(btn_viewpetugas);
        btn_viewpetugas.setLayout(btn_viewpetugasLayout);
        btn_viewpetugasLayout.setHorizontalGroup(
            btn_viewpetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewpetugasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        btn_viewpetugasLayout.setVerticalGroup(
            btn_viewpetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewpetugasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewpakan.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewpakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewpakanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewpakanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewpakanMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data Pemberian Pakan");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/pill-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewpakanLayout = new javax.swing.GroupLayout(btn_viewpakan);
        btn_viewpakan.setLayout(btn_viewpakanLayout);
        btn_viewpakanLayout.setHorizontalGroup(
            btn_viewpakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewpakanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewpakanLayout.setVerticalGroup(
            btn_viewpakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewpakanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewpemijahan.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewpemijahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewpemijahanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewpemijahanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewpemijahanMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data Pemijahan");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/eggs-2-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewpemijahanLayout = new javax.swing.GroupLayout(btn_viewpemijahan);
        btn_viewpemijahan.setLayout(btn_viewpemijahanLayout);
        btn_viewpemijahanLayout.setHorizontalGroup(
            btn_viewpemijahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewpemijahanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewpemijahanLayout.setVerticalGroup(
            btn_viewpemijahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewpemijahanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewstokindukan.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewstokindukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewstokindukanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewstokindukanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewstokindukanMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Data Stok Indukan");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/fish-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewstokindukanLayout = new javax.swing.GroupLayout(btn_viewstokindukan);
        btn_viewstokindukan.setLayout(btn_viewstokindukanLayout);
        btn_viewstokindukanLayout.setHorizontalGroup(
            btn_viewstokindukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewstokindukanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewstokindukanLayout.setVerticalGroup(
            btn_viewstokindukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewstokindukanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewikan.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewikanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewikanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewikanMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Data Ikan");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/fish-7-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewikanLayout = new javax.swing.GroupLayout(btn_viewikan);
        btn_viewikan.setLayout(btn_viewikanLayout);
        btn_viewikanLayout.setHorizontalGroup(
            btn_viewikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewikanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewikanLayout.setVerticalGroup(
            btn_viewikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewikanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewopname.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewopname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewopnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewopnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewopnameMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Data Opname");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/package-2-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewopnameLayout = new javax.swing.GroupLayout(btn_viewopname);
        btn_viewopname.setLayout(btn_viewopnameLayout);
        btn_viewopnameLayout.setHorizontalGroup(
            btn_viewopnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewopnameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewopnameLayout.setVerticalGroup(
            btn_viewopnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewopnameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_viewpengadaan.setBackground(new java.awt.Color(97, 212, 195));
        btn_viewpengadaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewpengadaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewpengadaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewpengadaanMouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Riwayat Pengadaan");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/recurring-appointment-32.png"))); // NOI18N

        javax.swing.GroupLayout btn_viewpengadaanLayout = new javax.swing.GroupLayout(btn_viewpengadaan);
        btn_viewpengadaan.setLayout(btn_viewpengadaanLayout);
        btn_viewpengadaanLayout.setHorizontalGroup(
            btn_viewpengadaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_viewpengadaanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_viewpengadaanLayout.setVerticalGroup(
            btn_viewpengadaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_viewpengadaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_viewkolam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewharga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewpopulasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewpetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewpakan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewpemijahan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewstokindukan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewikan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewopname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewpengadaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btn_viewkolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewpopulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewpakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewpemijahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewstokindukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewopname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_viewpengadaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 363, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addContainerGap())
        );

        ChangePanel.setBackground(new java.awt.Color(36, 47, 65));
        ChangePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ChangePanel.setPreferredSize(new java.awt.Dimension(991, 575));
        ChangePanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout ChangePanelLayout = new javax.swing.GroupLayout(ChangePanel);
        ChangePanel.setLayout(ChangePanelLayout);
        ChangePanelLayout.setHorizontalGroup(
            ChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        ChangePanelLayout.setVerticalGroup(
            ChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ChangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ChangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewhargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewhargaMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,203,208));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(true);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Harga Ikan Dan Pakan");
    }//GEN-LAST:event_btn_viewhargaMouseClicked

    private void btn_viewpopulasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpopulasiMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,203,208));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(true);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Populasi");
    }//GEN-LAST:event_btn_viewpopulasiMouseClicked

    private void btn_viewkolamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewkolamMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,203,208));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(true);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Kolam");
    }//GEN-LAST:event_btn_viewkolamMouseClicked

    private void btn_viewpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpetugasMouseClicked
        // TODO add your handling code here:
        
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,203,208));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(true);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Petugas");
    }//GEN-LAST:event_btn_viewpetugasMouseClicked

    private void btn_viewhargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewhargaMouseEntered
        // TODO add your handling code here:
        btn_viewharga.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewhargaMouseEntered

    private void btn_viewpopulasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpopulasiMouseEntered
        // TODO add your handling code here:
        btn_viewpopulasi.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewpopulasiMouseEntered

    private void btn_viewpetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpetugasMouseEntered
        // TODO add your handling code here:
        btn_viewpetugas.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewpetugasMouseEntered

    private void btn_viewkolamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewkolamMouseEntered
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewkolamMouseEntered

    private void btn_viewkolamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewkolamMouseExited
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewkolamMouseExited

    private void btn_viewhargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewhargaMouseExited
        // TODO add your handling code here:
        btn_viewharga.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewhargaMouseExited

    private void btn_viewpopulasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpopulasiMouseExited
        // TODO add your handling code here:
        btn_viewpopulasi.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewpopulasiMouseExited

    private void btn_viewpetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpetugasMouseExited
        // TODO add your handling code here:
        btn_viewpetugas.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewpetugasMouseExited

    private void btn_viewpakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpakanMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,203,208));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(true);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Pemberian Pakan");
    }//GEN-LAST:event_btn_viewpakanMouseClicked

    private void btn_viewpakanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpakanMouseEntered
        // TODO add your handling code here:
        btn_viewpakan.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewpakanMouseEntered

    private void btn_viewpakanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpakanMouseExited
        // TODO add your handling code here:
        btn_viewpakan.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewpakanMouseExited

    private void btn_viewpemijahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpemijahanMouseClicked
        // TODO add your handling code here
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,203,208));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(true);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Pemijahan");
    }//GEN-LAST:event_btn_viewpemijahanMouseClicked

    private void btn_viewpemijahanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpemijahanMouseEntered
        // TODO add your handling code here:
        btn_viewpemijahan.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewpemijahanMouseEntered

    private void btn_viewpemijahanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpemijahanMouseExited
        // TODO add your handling code here:
        btn_viewpemijahan.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewpemijahanMouseExited

    private void btn_viewstokindukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewstokindukanMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,203,208));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(true);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Stok Indukan");
    }//GEN-LAST:event_btn_viewstokindukanMouseClicked

    private void btn_viewstokindukanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewstokindukanMouseEntered
        // TODO add your handling code here:
        btn_viewstokindukan.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewstokindukanMouseEntered

    private void btn_viewstokindukanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewstokindukanMouseExited
        // TODO add your handling code here:
        btn_viewstokindukan.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewstokindukanMouseExited

    private void btn_viewikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewikanMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,203,208));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(true);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(false);
        judul.setText("Data Ikan");
    }//GEN-LAST:event_btn_viewikanMouseClicked

    private void btn_viewikanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewikanMouseEntered
        // TODO add your handling code here:
        btn_viewikan.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewikanMouseEntered

    private void btn_viewikanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewikanMouseExited
        // TODO add your handling code here:
        btn_viewikan.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewikanMouseExited

    private void btn_viewopnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewopnameMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,203,208));
        btn_viewpengadaan.setBackground(new Color(97,212,195));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(true);
        v_pengadaan.setVisible(false);
        judul.setText("Data Opname");
    }//GEN-LAST:event_btn_viewopnameMouseClicked

    private void btn_viewopnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewopnameMouseEntered
        // TODO add your handling code here:
        btn_viewopname.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewopnameMouseEntered

    private void btn_viewopnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewopnameMouseExited
        // TODO add your handling code here:
        btn_viewopname.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewopnameMouseExited

    private void btn_viewpengadaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpengadaanMouseClicked
        // TODO add your handling code here:
        btn_viewkolam.setBackground(new Color(97,212,195));
        btn_viewharga.setBackground(new Color(97,212,195));
        btn_viewpopulasi.setBackground(new Color(97,212,195));
        btn_viewpetugas.setBackground(new Color(97,212,195));
        btn_viewpakan.setBackground(new Color(97,212,195));
        btn_viewpemijahan.setBackground(new Color(97,212,195));
        btn_viewikan.setBackground(new Color(97,212,195));
        btn_viewstokindukan.setBackground(new Color(97,212,195));
        btn_viewopname.setBackground(new Color(97,212,195));
        btn_viewpengadaan.setBackground(new Color(97,203,208));
        
        v_kolam.setVisible(false);
        v_harga.setVisible(false);
        v_populasi.setVisible(false);
        v_petugas.setVisible(false);
        v_dataikan.setVisible(false);
        v_pemijahan.setVisible(false);
        v_pakan.setVisible(false);
        v_stokindukan.setVisible(false);
        v_opname.setVisible(false);
        v_pengadaan.setVisible(true);
        judul.setText("Data Riwayat Pengadaan");
    }//GEN-LAST:event_btn_viewpengadaanMouseClicked

    private void btn_viewpengadaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpengadaanMouseEntered
        // TODO add your handling code here:
        btn_viewpengadaan.setBackground(new Color(97,203,208));
    }//GEN-LAST:event_btn_viewpengadaanMouseEntered

    private void btn_viewpengadaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewpengadaanMouseExited
        // TODO add your handling code here:
        btn_viewpengadaan.setBackground(new Color(97,212,195));
    }//GEN-LAST:event_btn_viewpengadaanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePanel;
    private javax.swing.JPanel btn_viewharga;
    private javax.swing.JPanel btn_viewikan;
    private javax.swing.JPanel btn_viewkolam;
    private javax.swing.JPanel btn_viewopname;
    private javax.swing.JPanel btn_viewpakan;
    private javax.swing.JPanel btn_viewpemijahan;
    private javax.swing.JPanel btn_viewpengadaan;
    private javax.swing.JPanel btn_viewpetugas;
    private javax.swing.JPanel btn_viewpopulasi;
    private javax.swing.JPanel btn_viewstokindukan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul;
    // End of variables declaration//GEN-END:variables
}
