/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewTable;

import java.awt.Color;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author REFKY
 */
public class TableStokIndukan extends javax.swing.JPanel {

    /**
     * Creates new form TableStokIndukan
     */
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    public TableStokIndukan() {
        initComponents();
        Koneksi.Koneksi databaseConnection = new Koneksi.Koneksi();
        con = databaseConnection.getKoneksi();
        showDataIndukan(false, "");
    }
    DefaultTableModel dtm;

    public void showDataIndukan(boolean search, String tipeSearch) {
        String[] kolom = {"ID Stok Indukan", "Nama Ikan", "Tanggal", "Banyak Induk Betina", "Banyak Induk Jantan", "Calon Induk Bentina", "Calon Induk Jantan", "Jumlah Kematian", "Petugas", "Keterangan"};
        dtm = new DefaultTableModel(null, kolom);
        try {
            Statement st = con.createStatement();
            String query = "SELECT * FROM stok_indukan "
                    + "INNER JOIN data_ikan ON (stok_indukan.id_ikan = data_ikan.id_ikan)"
                    + "INNER JOIN petugas ON (stok_indukan.id_petugas = petugas.id_petugas)";
            if (search) {
                query += "WHERE nama_ikan LIKE '%" + tipeSearch + "%'"
                        + "OR tanggal LIKE '%" + tipeSearch + "%'"
                        + "OR banyak_induk_betina LIKE '%" + tipeSearch + "%'"
                        + "OR banyak_induk_jantan LIKE '%" + tipeSearch + "%'"
                        + "OR calon_indukan_betina LIKE '%" + tipeSearch + "%'"
                        + "OR calon_indukan_jantan LIKE '%" + tipeSearch + "%'"
                        + "OR jumlah_kematian LIKE '%" + tipeSearch + "%'"
                        + "OR id_petugas LIKE '%" + tipeSearch + "%'"
                        + "OR keterangan LIKE '%" + tipeSearch + "%'";
            }

            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                String id_stokindukan = rs.getString("id_stok_indukan");
                String id_ikan = rs.getString("nama_ikan");
                String tanggal = rs.getString("tanggal");
                String banyak_betina = rs.getString("banyak_induk_betina");
                String banyak_jantan = rs.getString("banyak_induk_jantan");
                String calon_betina = rs.getString("calon_indukan_betina");
                String calon_jantan = rs.getString("calon_indukan_jantan");
                String kematian = rs.getString("jumlah_kematian");
                String petugas = rs.getString("nama_petugas");
                String keterangan = rs.getString("keterangan");

                dtm.addRow(new String[]{id_stokindukan, id_ikan, tanggal, banyak_betina, banyak_jantan, calon_betina, calon_jantan, kematian, petugas, keterangan});
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        table_stokindukan.setModel(dtm);
    }
    
    private String getCellValue(int x, int y) {
        return dtm.getValueAt(x, y).toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_stokindukan = new javax.swing.JTable();
        Search = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_hapussemua = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        table_stokindukan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_stokindukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Anggota", "Kelas", "Tanggal Dibuat", "Alamat"
            }
        ));
        table_stokindukan.setGridColor(new java.awt.Color(255, 255, 255));
        table_stokindukan.setSelectionBackground(new java.awt.Color(97, 212, 195));
        table_stokindukan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                table_stokindukanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table_stokindukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stokindukanMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_stokindukan);

        Search.setBackground(new java.awt.Color(36, 47, 65));
        Search.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setBorder(null);
        Search.setPreferredSize(new java.awt.Dimension(450, 39));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(36, 47, 65));
        btn_edit.setText("Edit");
        btn_edit.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(36, 47, 65));
        btn_hapus.setText("Hapus");
        btn_hapus.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_hapusMouseExited(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(255, 255, 255));
        btn_refresh.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(36, 47, 65));
        btn_refresh.setText("Tambah");
        btn_refresh.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_refreshMouseExited(evt);
            }
        });
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari");

        btn_hapussemua.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapussemua.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        btn_hapussemua.setForeground(new java.awt.Color(36, 47, 65));
        btn_hapussemua.setText("Hapus Semua");
        btn_hapussemua.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_hapussemua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hapussemuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_hapussemuaMouseExited(evt);
            }
        });
        btn_hapussemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapussemuaActionPerformed(evt);
            }
        });

        btnExport.setBackground(new java.awt.Color(255, 255, 255));
        btnExport.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        btnExport.setForeground(new java.awt.Color(36, 47, 65));
        btnExport.setText("Export Excel");
        btnExport.setPreferredSize(new java.awt.Dimension(100, 40));
        btnExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportMouseExited(evt);
            }
        });
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_hapussemua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(605, 605, 605)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapussemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_stokindukanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_table_stokindukanAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_table_stokindukanAncestorAdded

    private void table_stokindukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stokindukanMouseClicked

    }//GEN-LAST:event_table_stokindukanMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed

    }//GEN-LAST:event_SearchKeyPressed

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        // TODO add your handling code here:
        btn_edit.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // TODO add your handling code here:
        btn_edit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int baris = table_stokindukan.getSelectedRow();
        String selected = table_stokindukan.getValueAt(baris, 0).toString();
        TemplateAdmin.Tambah_Indukan edit_indukan = new TemplateAdmin.Tambah_Indukan(true, "Edit", selected);
        edit_indukan.setVisible(true);
        JFrame parent = (JFrame) this.getTopLevelAncestor();
        parent.dispose();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseEntered
        // TODO add your handling code here:
        btn_hapus.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_btn_hapusMouseEntered

    private void btn_hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseExited
        // TODO add your handling code here:
        btn_hapus.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_hapusMouseExited

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int baris = table_stokindukan.getSelectedRow();
        String idWhoWantToBeDelete = table_stokindukan.getValueAt(baris, 0).toString();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                Statement stmt = con.createStatement();
                String query = "DELETE FROM stok_indukan WHERE id_stok_indukan = '" + idWhoWantToBeDelete + "';";
                int berhasil = stmt.executeUpdate(query);
                System.out.println(query);
                if (berhasil == 1) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    dtm.getDataVector().removeAllElements();
                    showDataIndukan(false, "");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseEntered
        // TODO add your handling code here:
        btn_refresh.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_btn_refreshMouseEntered

    private void btn_refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseExited
        // TODO add your handling code here:
        btn_refresh.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_refreshMouseExited

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        TemplateAdmin.Tambah_Indukan tambah_indukan = new TemplateAdmin.Tambah_Indukan(true, "Tambah", "");
        tambah_indukan.setVisible(true);
        JFrame parent = (JFrame) this.getTopLevelAncestor();
        parent.dispose();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String isi = Search.getText();
        if (Character.isDigit(c)) {
            showDataIndukan(true, isi);
        }
        if (!Character.isDigit(c)) {
            showDataIndukan(true, isi);
        }
    }//GEN-LAST:event_SearchKeyReleased

    private void btnExportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportMouseEntered

    private void btnExportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportMouseExited

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        FileOutputStream excelFOU = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook excelJTableExporter = null;
        JFileChooser excelFileChooser = new JFileChooser();
        excelFileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Excel Files", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            try {
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("Stok Indukan");
                TreeMap<String, Object[]> data = new TreeMap<>();
                data.put("-1", new Object[]{dtm.getColumnName(0), dtm.getColumnName(1), dtm.getColumnName(2), dtm.getColumnName(3), dtm.getColumnName(4), dtm.getColumnName(5), dtm.getColumnName(6), dtm.getColumnName(7), dtm.getColumnName(8), dtm.getColumnName(9)});
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    data.put(Integer.toString(i), new Object[]{getCellValue(i, 0), getCellValue(i, 1), getCellValue(i, 2), getCellValue(i, 3), getCellValue(i, 4), getCellValue(i, 5), getCellValue(i, 6), getCellValue(i, 7), getCellValue(i, 8), getCellValue(i, 9)});
                    Set<String> ids = data.keySet();
                    XSSFRow row;
                    int rowID = 0;

                    for (String key : ids) {
                        row = excelSheet.createRow(rowID++);

                        Object[] values = data.get(key);

                        int cellID = 0;
                        for (Object o : values) {
                            XSSFCell cell = row.createCell(cellID++);
                            cell.setCellValue(o.toString());
                        }
                    }
                }
                excelFOU = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(null, "Berhasil Ekspor");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelFOU != null) {
                        excelFOU.close();
                    }
                    if (excelJTableExporter != null) {
                        excelJTableExporter.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btn_hapussemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapussemuaActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus semua data?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                Statement stmt = con.createStatement();
                String query = "TRUNCATE TABLE stok_indukan";
                int berhasil = stmt.executeUpdate(query);
                if (berhasil == 1) {
                    JOptionPane.showMessageDialog(null, "Semua Data Gagal Dihapus");
                } else {
                    JOptionPane.showMessageDialog(null, "Semua Data Berhasil Dihapus");
                    int rowCount = dtm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dtm.removeRow(i);
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_hapussemuaActionPerformed

    private void btn_hapussemuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapussemuaMouseExited
        // TODO add your handling code here:
        btn_hapussemua.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_hapussemuaMouseExited

    private void btn_hapussemuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapussemuaMouseEntered
        // TODO add your handling code here:
        btn_hapussemua.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_btn_hapussemuaMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hapussemua;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table_stokindukan;
    // End of variables declaration//GEN-END:variables
}
